# Generated by Django 3.2.13 on 2022-04-26 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Recommendation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addcolleges',
            name='college_data',
        ),
    ]
