# Generated by Django 3.2.13 on 2022-04-26 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recommendation', '0002_remove_addcolleges_college_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='addcolleges',
            name='college_data',
            field=models.ManyToManyField(to='Recommendation.Review'),
        ),
    ]
