# Generated by Django 3.2.13 on 2022-04-26 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recommendation', '0003_addcolleges_college_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addcolleges',
            name='college_data',
        ),
        migrations.AddField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=4),
            preserve_default=False,
        ),
    ]
