# Generated by Django 3.2.13 on 2022-04-26 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Recommendation', '0004_auto_20220426_1713'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='created_at',
        ),
    ]
